version: "3.9"
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    volumes:
      - "/Users/solvd/IdeaProjects/infoprice-testing/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/solvd/IdeaProjects/infoprice-testing/config/video:/opt/selenoid/video"
      - "/Users/solvd/IdeaProjects/infoprice-testing/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/solvd/IdeaProjects/infoprice-testing/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4445:4444"
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  ggr:
    network_mode: bridge
    image: aerokube/ggr:latest-release
    volumes:
      - "/Users/solvd/IdeaProjects/infoprice-testing/grid-router/quota:/etc/grid-router:ro"
    links:
      - selenoid
    ports:
      - "4444:4444"